version: '3'

services:
  pg_db_in:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata/in:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432
    networks:
      - compose-network

  pg_db_out:
    image: postgres:12
    environment:
      POSTGRES_DB: pg_db_out
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
    volumes:
      - ./dbdata/out:/var/lib/postgresql/data
      - ./data/pg_db_out.sql:/docker-entrypoint-initdb.d/pg_db_out.sql
    ports:
      - 5433:5432
    networks:
      - compose-network
    
networks: 
  compose-network:
    driver: bridge